version: '3'

services:
  web:
    build:
      context: .
    command: >
            bash -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
    restart: always
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: .
    restart: always
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    depends_on:
      - web
      - redis
  
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
  